### ISSUE TITLE
Tool does not detect Starfield running when using SFSE

### ISSUE THREAD

**Issue by smolgumball** [SomeCrazyGuy/LiveINI-Starfield#2]
Hi there, thank you for the wonderful tool!

I'm running Starfield via SFSE via Steam, using the "renamed EXE method" which allows for Steam to load Starfield as normal and maintain playtime tracking + Steam overlay support.

When attempting to use LiveINI, I simply receive the "Starfield is not running" notice when pressing "Scan Starfield."

### Environment setup goes something like:

1. Download latest SFSE from Nexus
2. Place files into `steamapps/common/Starfield` directory
3. Place an additional `SFSE.ini` file into `steamapps/common/Starfield/Data/SFSE` directory
4. Rename `steamapps/common/Starfield/Starfield.exe` to `StarfieldVanilla.exe`
5. Rename `steamapps/common/Starfield/sfse_loader.exe` to `Starfield.exe`

The additional `SFSE.ini` file contains basic SFSE loader config:

```ini
[Loader]
RuntimeName=StarfieldVanilla.exe
```

I imagine that LiveINI may support using SFSE via the standard `sfse_loader.exe` executable, but I haven't actually tested this. Assumptions, sorry!

If SFSE is supported generally, I wonder if LiveINI could also take into account the `SFSE.ini` loader configuration in case executable names need to be disambiguated? I realize this would likely require the user to point LiveINI to their game directory, but I thought I'd toss the issue out none the less.

Thanks again for the tool, and kudos for a nice + tidy ImGui UI 😄

**Comment by SomeCrazyGuy** [comment]
I will look into this, I probably wont parse the sfse ini, but perhaps try a few heuristics like the window title to find the right application.

**Comment by SomeCrazyGuy** [comment]
I added a fallback detection method by checking if there is a window with the title "Starfield" and opening that process. This method is used only as a fallback because of the possibility of false-positives (you might have windows explorer open in the starfield directory and windows explorer will title its window the same as the directory name)
